### ISSUE TITLE
Add requirements.txt to project

### ISSUE THREAD

**Issue by CodingJonas** [saiboxx/ml-showcases#1]
What's the reason behind installing[ all python dependencies through docker](https://github.com/saiboxx/ml-showcases/blob/ba256f819659958db089fa356e19fac59b4b3016/anime-autoencoder/app/app/Dockerfile#L4)? I think handling this in a requirements.txt file and simply installing all dependencies through this inside the Dockerfile makes the project more readable and more maintainable.

**Comment by saiboxx** [comment]
You're right. Thanks for the hint.
A .txt has been added with bc92468. ;)
